steps:
  - name: gcr.io/cloud-builders/bash
    entrypoint: bash
    args:
      - -c
      - |
        cp pyproject.toml dbt/pyproject.toml
        cp uv.lock dbt/uv.lock

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api-warehouse-dbt:$COMMIT_SHA
      - -f
      - dbt/Dockerfile
      - dbt

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - ${_JOB_NAME}
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api-warehouse-dbt:$COMMIT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api-warehouse-dbt:$COMMIT_SHA

substitutions:
  _REGION: us-central1
  _REPOSITORY: api-warehouse
  _JOB_NAME: api-warehouse-dbt
