"""add trakt schema

Revision ID: 2a5b4d4826a6
Revises: a3977bc0591e
Create Date: 2026-07-01 09:45:17.924137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a5b4d4826a6'
down_revision: Union[str, Sequence[str], None] = 'a3977bc0591e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS trakt")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_episodes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('episode_season', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('episode_title', sa.String(), nullable=True),
    sa.Column('episode_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('show_title', sa.String(), nullable=True),
    sa.Column('show_year', sa.Integer(), nullable=True),
    sa.Column('show_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['config.api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', name='uq_trakt_watched_episodes_history_id'),
    schema='trakt'
    )
    op.create_table('watched_movies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('movie_title', sa.String(), nullable=True),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('movie_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['config.api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', name='uq_trakt_watched_movies_history_id'),
    schema='trakt'
    )
    op.create_table('watchlist_movies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('movie_title', sa.String(), nullable=True),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('movie_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['config.api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', name='uq_trakt_watchlist_movies_watchlist_id'),
    schema='trakt'
    )
    op.create_table('watchlist_shows',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('show_title', sa.String(), nullable=True),
    sa.Column('show_year', sa.Integer(), nullable=True),
    sa.Column('show_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['config.api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', name='uq_trakt_watchlist_shows_watchlist_id'),
    schema='trakt'
    )
    op.drop_index(op.f('uq_recent_track_now_playing'), table_name='recent_tracks', schema='music', postgresql_where='(date_uts IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_recent_track_now_playing'), 'recent_tracks', ['artist_name', 'name'], unique=True, schema='music', postgresql_where='(date_uts IS NULL)')
    op.drop_table('watchlist_shows', schema='trakt')
    op.drop_table('watchlist_movies', schema='trakt')
    op.drop_table('watched_movies', schema='trakt')
    op.drop_table('watched_episodes', schema='trakt')
    op.execute("DROP SCHEMA IF EXISTS trakt")
    # ### end Alembic commands ###
