"""trakt bigint ids

Revision ID: 439e1fd5ebb0
Revises: 2a5b4d4826a6
Create Date: 2026-07-01 09:54:31.124586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439e1fd5ebb0'
down_revision: Union[str, Sequence[str], None] = '2a5b4d4826a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watched_episodes', 'history_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watched_movies', 'history_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watchlist_movies', 'watchlist_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watchlist_shows', 'watchlist_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='trakt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist_shows', 'watchlist_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watchlist_movies', 'watchlist_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watched_movies', 'history_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='trakt')
    op.alter_column('watched_episodes', 'history_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='trakt')
    # ### end Alembic commands ###
