"""trakt personal movie ratings

Revision ID: 9f829f0ec0f9
Revises: cfcf71c9b18b
Create Date: 2026-07-08 10:01:17.572209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f829f0ec0f9'
down_revision: Union[str, Sequence[str], None] = 'cfcf71c9b18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_movies', sa.Column('my_rating', sa.Float(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('my_rated_at', sa.DateTime(timezone=True), nullable=True), schema='trakt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_movies', 'my_rated_at', schema='trakt')
    op.drop_column('watched_movies', 'my_rating', schema='trakt')
    # ### end Alembic commands ###
