"""add listened_at to recent_tracks

Revision ID: ac162c1bec24
Revises: 2278a53cca40
Create Date: 2026-06-23 17:42:44.743518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac162c1bec24'
down_revision: Union[str, Sequence[str], None] = '2278a53cca40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recent_tracks', sa.Column('listened_at', sa.DateTime(timezone=True), sa.Computed('to_timestamp(date_uts::integer)', persisted=True), nullable=True), schema='music')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recent_tracks', 'listened_at', schema='music')
    # ### end Alembic commands ###
