"""trakt extended fields

Revision ID: cfcf71c9b18b
Revises: 439e1fd5ebb0
Create Date: 2026-07-01 10:34:12.111084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfcf71c9b18b'
down_revision: Union[str, Sequence[str], None] = '439e1fd5ebb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_episodes', sa.Column('episode_number_abs', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('episode_overview', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('episode_runtime', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('episode_rating', sa.Float(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('episode_first_aired', sa.DateTime(timezone=True), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_overview', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_network', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_status', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_rating', sa.Float(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_homepage', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_runtime', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_country', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_certification', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_first_aired', sa.DateTime(timezone=True), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_aired_episodes', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_episodes', sa.Column('show_airs', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_tagline', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_overview', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_released', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_runtime', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_country', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_trailer', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_homepage', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_status', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_rating', sa.Float(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_votes', sa.Integer(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_language', sa.String(), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='trakt')
    op.add_column('watched_movies', sa.Column('movie_certification', sa.String(), nullable=True), schema='trakt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_movies', 'movie_certification', schema='trakt')
    op.drop_column('watched_movies', 'movie_genres', schema='trakt')
    op.drop_column('watched_movies', 'movie_language', schema='trakt')
    op.drop_column('watched_movies', 'movie_votes', schema='trakt')
    op.drop_column('watched_movies', 'movie_rating', schema='trakt')
    op.drop_column('watched_movies', 'movie_status', schema='trakt')
    op.drop_column('watched_movies', 'movie_homepage', schema='trakt')
    op.drop_column('watched_movies', 'movie_trailer', schema='trakt')
    op.drop_column('watched_movies', 'movie_country', schema='trakt')
    op.drop_column('watched_movies', 'movie_runtime', schema='trakt')
    op.drop_column('watched_movies', 'movie_released', schema='trakt')
    op.drop_column('watched_movies', 'movie_overview', schema='trakt')
    op.drop_column('watched_movies', 'movie_tagline', schema='trakt')
    op.drop_column('watched_episodes', 'show_airs', schema='trakt')
    op.drop_column('watched_episodes', 'show_aired_episodes', schema='trakt')
    op.drop_column('watched_episodes', 'show_first_aired', schema='trakt')
    op.drop_column('watched_episodes', 'show_certification', schema='trakt')
    op.drop_column('watched_episodes', 'show_country', schema='trakt')
    op.drop_column('watched_episodes', 'show_genres', schema='trakt')
    op.drop_column('watched_episodes', 'show_runtime', schema='trakt')
    op.drop_column('watched_episodes', 'show_homepage', schema='trakt')
    op.drop_column('watched_episodes', 'show_rating', schema='trakt')
    op.drop_column('watched_episodes', 'show_status', schema='trakt')
    op.drop_column('watched_episodes', 'show_network', schema='trakt')
    op.drop_column('watched_episodes', 'show_overview', schema='trakt')
    op.drop_column('watched_episodes', 'episode_first_aired', schema='trakt')
    op.drop_column('watched_episodes', 'episode_rating', schema='trakt')
    op.drop_column('watched_episodes', 'episode_runtime', schema='trakt')
    op.drop_column('watched_episodes', 'episode_overview', schema='trakt')
    op.drop_column('watched_episodes', 'episode_number_abs', schema='trakt')
    # ### end Alembic commands ###
